dist: bionic
language: node_js
node_js:
  - 12.4.0
env:
  matrix:
    - MONGODB_VERSION=stable MONGODB_TOPOLOGY=standalone
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - libkrb5-dev
      - libsecret-1-dev
install: npm ci
cache: npm
script:
  - npm run cover
  - npm run test:karma
after_success:
  - npm run storybook:ghpages
deploy:
  # Push to GitHub Pages
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local_dir: .ghpages
    on:
      branch: master